version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
  mongo:
    image: mongo:5
    ports:
      - "27017:27017"
